"""
Gerar Manual do Usuario para Adriana Wagner
Wagner Perfumes — Guia Rapido + Agente IA
"""

from fpdf import FPDF
import os

class ManualPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font('Helvetica', 'I', 7)
            self.set_text_color(180, 160, 140)
            self.cell(0, 6, 'Wagner Perfumes - Manual do Usuario', 0, 1, 'R')
            self.set_draw_color(201, 166, 70)
            self.line(10, 12, 200, 12)
            self.ln(4)
    
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 7)
        self.set_text_color(180, 160, 140)
        self.cell(0, 8, f'Pagina {self.page_no()}', 0, 0, 'C')

    def titulo(self, texto, tamanho=16):
        self.set_font('Helvetica', 'B', tamanho)
        self.set_text_color(58, 31, 24)
        self.cell(0, 10, texto, 0, 1)
        self.set_draw_color(201, 166, 70)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def subtitulo(self, texto, tamanho=12):
        self.set_font('Helvetica', 'B', tamanho)
        self.set_text_color(155, 79, 53)
        self.cell(0, 8, texto, 0, 1)
        self.ln(2)

    def texto(self, texto, tamanho=10):
        self.set_font('Helvetica', '', tamanho)
        self.set_text_color(58, 31, 24)
        self.multi_cell(0, 6, texto)
        self.ln(2)

    def destaque(self, texto, tamanho=10):
        self.set_font('Helvetica', 'B', tamanho)
        self.set_text_color(201, 166, 70)
        self.multi_cell(0, 6, texto)
        self.ln(1)

    def bullet(self, texto, indent=10):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(58, 31, 24)
        x = self.get_x()
        self.set_x(x + indent)
        self.cell(5, 6, '-')
        self.multi_cell(0, 6, texto)
        self.ln(1)

    def caixa_destaque(self, texto):
        self.set_fill_color(255, 247, 241)
        self.set_draw_color(201, 166, 70)
        y = self.get_y()
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(155, 79, 53)
        self.set_x(15)
        self.multi_cell(180, 6, texto, border=1, fill=True)
        self.ln(4)


pdf = ManualPDF()
pdf.set_auto_page_break(auto=True, margin=20)
pdf.add_page()

# ===== CAPA =====
pdf.ln(30)
pdf.set_font('Helvetica', 'B', 28)
pdf.set_text_color(201, 166, 70)
pdf.cell(0, 14, 'WAGNER PERFUMES', 0, 1, 'C')
pdf.set_font('Helvetica', '', 16)
pdf.set_text_color(58, 31, 24)
pdf.cell(0, 10, 'Manual do Usuario', 0, 1, 'C')
pdf.ln(5)
pdf.set_draw_color(201, 166, 70)
pdf.line(60, pdf.get_y(), 150, pdf.get_y())
pdf.ln(10)
pdf.set_font('Helvetica', '', 11)
pdf.set_text_color(120, 120, 120)
pdf.cell(0, 7, 'Sua loja virtual de perfumes', 0, 1, 'C')
pdf.cell(0, 7, 'JC Infocell - Desenvolvido por Jaquelino', 0, 1, 'C')
pdf.cell(0, 7, 'Maio de 2026', 0, 1, 'C')

# ===== SUMARIO =====
pdf.add_page()
pdf.titulo('Sumario')
pdf.texto('1. O que e o sistema?', 10)
pdf.texto('2. Como acessar', 10)
pdf.texto('3. Como funciona a loja', 10)
pdf.texto('4. Gerenciando sem trabalho - Agente de IA', 10)
pdf.texto('5. Usando o Painel Admin', 10)
pdf.texto('6. Gerenciando Produtos', 10)
pdf.texto('7. Acompanhando Pedidos', 10)
pdf.texto('8. Promocao do Mes das Maes', 10)
pdf.texto('9. Duvidas Frequentes', 10)

# ===== CAP 1 =====
pdf.add_page()
pdf.titulo('1. O que e o sistema?')
pdf.texto('Parabens, Adriana! Sua loja virtual ja esta no ar!')
pdf.texto('')
pdf.texto('O Wagner Perfumes e um site de vendas completo onde seus clientes podem:')
pdf.bullet('Ver os perfumes disponiveis na loja')
pdf.bullet('Escolher por categoria (Masculino, Feminino, Unissex, Premium)')
pdf.bullet('Adicionar produtos no carrinho')
pdf.bullet('Finalizar a compra com PIX (QR Code) ou cartao de credito')
pdf.bullet('Preencher endereco para entrega')
pdf.texto('')
pdf.texto('Tudo funciona pelo celular, tablet ou computador.')

# ===== CAP 2 =====
pdf.add_page()
pdf.titulo('2. Como acessar')
pdf.texto('Para acessar a loja, voce precisa:')
pdf.bullet('Estar na rede ZeroTier (ja configurada pelo Jaquelino)')
pdf.bullet('Digitar o endereco no navegador do celular ou PC')
pdf.texto('')
pdf.destaque('Endereco da Loja:')
pdf.caixa_destaque('http://10.242.205.212:5000')
pdf.texto('')
pdf.destaque('Endereco do Painel Admin:')
pdf.caixa_destaque('http://10.242.205.212:5000/admin')
pdf.texto('')
pdf.texto('Guarde esses enderecos! E por eles que voce vai gerenciar tudo.')

# ===== CAP 3 =====
pdf.add_page()
pdf.titulo('3. Como funciona a loja')
pdf.texto('A pagina inicial da loja mostra:')
pdf.texto('')
pdf.texto('1. BANNER DE PROMOCAO')
pdf.bullet('Foto bonita de mae com bebe')
pdf.bullet('Frase de promocao do Mes das Maes')
pdf.bullet('Botoes para ver perfumes ou o regulamento')
pdf.texto('')
pdf.texto('2. PERFUMES EM DESTAQUE')
pdf.bullet('Grade com fotos reais dos perfumes')
pdf.bullet('Nome, marca, preco e botao COMPRAR')
pdf.texto('')
pdf.texto('3. CATEGORIAS')
pdf.bullet('Masculino, Feminino, Unissex, Premium')
pdf.bullet('Cada uma com foto de fundo')
pdf.texto('')
pdf.texto('4. PROMOCAO')
pdf.bullet('Explicacao da promocao do Mes das Maes')
pdf.bullet('Botao para comprar pelo WhatsApp')
pdf.texto('')
pdf.texto('5. FINALIZAR COMPRA')
pdf.texto('O cliente preenche nome, endereco, escolhe PIX ou cartao, e finaliza. Se for PIX, aparece um QR Code na hora pra pagar.')

# ===== CAP 4 =====
pdf.add_page()
pdf.titulo('4. Gerenciando sem trabalho - Agente de IA')
pdf.texto('Voce pode escolher entre duas formas de gerenciar sua loja:')
pdf.texto('')
pdf.texto('OPCAO 1 - FAZER VOCE MESMA (gratis)')
pdf.texto('Usar o Painel Admin (explicado no proximo capitulo).')
pdf.texto('Voce mesma adiciona produtos, ve pedidos, altera precos.')
pdf.texto('')
pdf.destaque('OPCAO 2 - AGENTE DE IA (recomendado - aluguel mensal)')
pdf.texto('')
pdf.texto('Que tal nunca precisar mexer em painel?')
pdf.texto('Com o Agente de IA, voce faz tudo pelo WhatsApp:')
pdf.texto('')
pdf.texto('EXEMPLOS DO QUE VOCE PODE PEDIR:')
pdf.caixa_destaque('"Adiciona um perfume novo: Malbec, masculino, R$ 189,90"')
pdf.caixa_destaque('"Muda o preco do Flora Radiante pra R$ 159,90"')
pdf.caixa_destaque('"Quantos pedidos recebi essa semana?"')
pdf.caixa_destaque('"Desativa o perfume tal da vitrine"')
pdf.caixa_destaque('"Qual foi a receita total ate agora?"')
pdf.caixa_destaque('"Adiciona a categoria VIP com 3 perfumes novos"')
pdf.texto('')
pdf.texto('Vantagens do Agente de IA:')
pdf.bullet('Nao precisa aprender nada - so falar o que quer')
pdf.bullet('Funciona pelo celular, pelo WhatsApp')
pdf.bullet('Responde em segundos')
pdf.bullet('Parece magica - seus clientes vao achar incrivel')
pdf.texto('')
pdf.texto('Para contratar o Agente de IA, fale com o Jaquelino e descubra o plano ideal para voce!')

# ===== CAP 5 =====
pdf.add_page()
pdf.titulo('5. Usando o Painel Admin')
pdf.texto('O Painel Admin e o "centro de controle" da sua loja.')
pdf.texto('Para acessar, abra o navegador e digite:')
pdf.caixa_destaque('http://10.242.205.212:5000/admin')
pdf.texto('')
pdf.texto('O painel tem 3 abas no menu lateral esquerdo:')
pdf.texto('')
pdf.texto('ABA 1 - PEDIDOS')
pdf.bullet('Mostra todos os pedidos recebidos')
pdf.bullet('Ve data, nome do cliente, telefone, itens, valor')
pdf.bullet('Ve se o pagamento foi PIX ou cartao')
pdf.bullet('Botoes: Enviar, Entregar, Excluir')
pdf.bullet('Filtro: Todos / Recebidos / Enviados / Entregues')
pdf.texto('')
pdf.texto('ABA 2 - PRODUTOS')
pdf.bullet('Lista todos os perfumes cadastrados')
pdf.bullet('Formulario para adicionar perfume novo')
pdf.bullet('Botoes: Editar, Excluir')
pdf.texto('')
pdf.texto('ABA 3 - CONFIGURACOES')
pdf.bullet('Alterar nome da loja')
pdf.bullet('Alterar telefone do WhatsApp')
pdf.bullet('Alterar chave PIX')
pdf.bullet('Alterar texto da promocao')
pdf.bullet('Ver estatisticas da loja')
pdf.texto('')
pdf.texto('No topo do painel voce ve:')
pdf.bullet('Numero total de pedidos')
pdf.bullet('Quantos produtos cadastrados')
pdf.bullet('Receita total (soma de todos os pedidos)')

# ===== CAP 6 =====
pdf.add_page()
pdf.titulo('6. Gerenciando Produtos')
pdf.texto('Para ADICIONAR um perfume novo:')
pdf.bullet('Va ate a aba PRODUTOS no painel')
pdf.bullet('Preencha: Nome, Marca, Preco, Categoria, Descricao')
pdf.bullet('No campo IMAGEM, escreva o nome do arquivo da foto')
pdf.bullet('Clique em SALVAR PRODUTO')
pdf.texto('')
pdf.texto('Dica: As imagens disponiveis estao na pasta imagens do sistema. Se quiser usar uma foto nova, o Jaquelino ou o Agente de IA pode colocar pra voce.')
pdf.texto('')
pdf.texto('Para EDITAR um perfume:')
pdf.bullet('Na lista de produtos, clique em EDITAR')
pdf.bullet('O formulario vai carregar os dados do perfume')
pdf.bullet('Altere o que quiser e clique em ATUALIZAR')
pdf.texto('')
pdf.texto('Para EXCLUIR um perfume:')
pdf.bullet('Clique no botao de lixeira ao lado do produto')
pdf.bullet('Confirme a exclusao')

# ===== CAP 7 =====
pdf.add_page()
pdf.titulo('7. Acompanhando Pedidos')
pdf.texto('Quando um cliente faz um pedido na loja:')
pdf.bullet('O pedido aparece automaticamente no painel')
pdf.bullet('Voce ve o nome, telefone, o que comprou e o valor')
pdf.bullet('Ve tambem o endereco de entrega')
pdf.texto('')
pdf.texto('Passo a passo para atender um pedido:')
pdf.texto('1. Entre no PAINEL ADMIN')
pdf.texto('2. Va na aba PEDIDOS')
pdf.texto('3. Veja quem comprou e o que comprou')
pdf.texto('4. Entre em contato com o cliente pelo WhatsApp')
pdf.texto('5. Confirme o pagamento (se for PIX, veja se caiu na conta)')
pdf.texto('6. Prepare o perfume para entrega')
pdf.texto('7. Clique em ENVIAR quando despachar')
pdf.texto('8. Clique em ENTREGAR quando o cliente receber')
pdf.texto('')
pdf.texto('Os status do pedido:')
pdf.bullet('Recebido (amarelo) - pedido novo, aguardando')
pdf.bullet('Enviado (verde) - ja foi despachado')
pdf.bullet('Entregue (azul) - cliente recebeu')

# ===== CAP 8 =====
pdf.add_page()
pdf.titulo('8. Promocao do Mes das Maes')
pdf.texto('A loja ja esta configurada com a promocao:')
pdf.texto('')
pdf.caixa_destaque('Concorra a R$ 300 em vale-compras!')
pdf.texto('')
pdf.texto('Como funciona a promocao:')
pdf.bullet('A cada perfume comprado, o cliente concorre automaticamente')
pdf.bullet('O sorteio e feito no Dia das Maes')
pdf.bullet('O premio e R$ 300 em vale-compras na loja')
pdf.texto('')
pdf.texto('Para alterar o texto da promocao:')
pdf.bullet('Acesse o PAINEL ADMIN')
pdf.bullet('Va na aba CONFIG')
pdf.bullet('Altere o campo "Mensagem da Promocao"')
pdf.texto('')
pdf.texto('Voce pode criar novas promocoes quando quiser!')

# ===== CAP 9 =====
pdf.add_page()
pdf.titulo('9. Duvidas Frequentes')
pdf.texto('')
pdf.subtitulo('Preciso instalar algo no meu celular?')
pdf.texto('Nao! Basta ter o ZeroTier instalado (o Jaquelino ja configura pra voce) e abrir o navegador.')
pdf.texto('')
pdf.subtitulo('Os pagamentos caem na minha conta?')
pdf.texto('O PIX gera um QR Code para o cliente pagar. A chave PIX configurada e a sua. O dinheiro cai direto na sua conta.')
pdf.texto('')
pdf.subtitulo('E se eu errar alguma coisa no painel?')
pdf.texto('Nao se preocupe. Tudo pode ser editado, excluido ou corrigido. Se travar, chama o Jaquelino.')
pdf.texto('')
pdf.subtitulo('Posso vender outros produtos alem de perfumes?')
pdf.texto('Sim! O sistema aceita qualquer tipo de produto. So cadastrar no painel.')
pdf.texto('')
pdf.subtitulo('O que e melhor: Painel Admin ou Agente de IA?')
pdf.texto('Se voce gosta de mexer e ter controle total, use o PAINEL. Se prefere praticidade e nao quer aprender nada, alugue o AGENTE DE IA.')
pdf.texto('')
pdf.subtitulo('Quanto custa o Agente de IA?')
pdf.texto('Pergunte ao Jaquelino! O valor e acessivel e voce pode testar antes de contratar.')
pdf.texto('')
pdf.subtitulo('O site fica no meu computador? E se desligar?')
pdf.texto('Enquanto for teste, sim. Quando quiser profissionalizar, podemos subir para um servidor na nuvem que fica ligado 24h.')

# ===== FINAL =====
pdf.add_page()
pdf.ln(40)
pdf.set_font('Helvetica', 'B', 20)
pdf.set_text_color(201, 166, 70)
pdf.cell(0, 12, 'Bem-vinda ao mundo digital!', 0, 1, 'C')
pdf.ln(5)
pdf.set_font('Helvetica', '', 12)
pdf.set_text_color(58, 31, 24)
pdf.cell(0, 7, 'Wagner Perfumes - Sucesso nas vendas online!', 0, 1, 'C')
pdf.ln(10)
pdf.set_draw_color(201, 166, 70)
pdf.line(60, pdf.get_y(), 150, pdf.get_y())
pdf.ln(10)
pdf.set_font('Helvetica', 'I', 10)
pdf.set_text_color(120, 120, 120)
pdf.cell(0, 7, 'Duvidas? Fale com o Jaquelino', 0, 1, 'C')
pdf.cell(0, 7, 'JC Infocell', 0, 1, 'C')

# Salvar
output = r'C:\Dev\_SISTEMAS\WagnerPerfumes\docs\MANUAL_USUARIO_Wagner_Perfumes.pdf'
pdf.output(output)
print(f"PDF gerado: {output}")
print(f"Tamanho: {os.path.getsize(output)} bytes")
print(f"Paginas: {pdf.page_no()}")
